# Generated by Django 4.2.24 on 2025-10-04 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kartu',
            fields=[
                ('kartu_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('gambar', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KisahSosial',
            fields=[
                ('kisah_id', models.AutoField(primary_key=True, serialize=False)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('score_human', models.FloatField()),
                ('score_perplexity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kartu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aac_apps.kartu')),
            ],
        ),
    ]
