# Generated by Django 5.2.7 on 2025-10-10 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aac_apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisahsosial',
            name='kartu_id',
        ),
        migrations.AddField(
            model_name='kartu',
            name='kategori',
            field=models.TextField(default='default'),
        ),
        migrations.CreateModel(
            name='KartuKisah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kartu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aac_apps.kartu')),
                ('kisah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aac_apps.kisahsosial')),
            ],
            options={
                'unique_together': {('kartu', 'kisah')},
            },
        ),
        migrations.AddField(
            model_name='kisahsosial',
            name='kartu',
            field=models.ManyToManyField(through='aac_apps.KartuKisah', to='aac_apps.kartu'),
        ),
    ]
