# Generated by Django 4.2.24 on 2025-10-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aac_apps', '0002_remove_kisahsosial_kartu_id_kartu_kategori_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kartukisah',
            unique_together=set(),
        ),
    ]
