# Generated by Django 4.2.24 on 2025-10-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aac_apps', '0003_alter_kartukisah_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='kartukisah',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
