# Generated by Django 5.2.7 on 2025-10-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aac_apps', '0004_kartukisah_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='kartu',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
